name: my-first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "Hello World"
            echo "This is done. Good Bye"
#      - name: Print Goodbye
#        run: echo "This is done. Good Bye"
